version: '3'

tasks:
  setup:
    desc: Verify repo location and required symlinks
    deps:
      - ensure-sh
      - ensure-ssh-config
    cmds:
      - ./sh/check-config-setup.sh
    silent: true

  ensure-ssh-config:
    desc: Ensure ~/.ssh/config points to repo-managed config
    cmds:
      - task -d i setup
    silent: true

  ensure-sh:
    desc: Ensure nikivdev/sh repo is present
    cmds:
      - |
        set -eu
        if [ -d sh/.git ]; then
          git -C sh remote get-url origin >/dev/null 2>&1 || {
            echo "[x] sh repo exists but origin is missing" >&2
            exit 1
          }
          echo "[ok] sh repo present"
        elif [ -e sh ]; then
          echo "[x] sh directory exists but is not a git repo. Remove or rename it, then rerun task setup." >&2
          exit 1
        else
          echo "[info] cloning https://github.com/nikivdev/sh.git into ./sh"
          git clone https://github.com/nikivdev/sh.git sh
        fi
    silent: true
